# EasyMosdns Client v3.0
# ----------------------
# 使用前请修改以下位置：
# 98行  addr: "223.5.5.5" 可以改成其它大厂DNS或无劫持的本地运营商DNS
# 105行 addr: "https://edns.apad.pro:3306/dns-query" 必须修改成新节点的地址
# 108行 enable_http3: true 如果选择了不支持H3的节点需要改成false
# 115行 addr: "tls://8.8.4.4:853" 可以修改成其它备用的海外节点
# ad_domain_list.txt 可以在其中添加自己的屏蔽规则
# ecs_cn_domain.txt  可以在其中添加强制使用本地DNS的域名进行加速解析
# 配置文件结尾端口号(默认5353)可根据需求自行修改

log:
    file: "./mosdns.log"
    level: error

data_providers:
  - tag: chinalist
    file: ./rules/china_domain_list.txt
    auto_reload: true
  - tag: cdncn
    file: ./rules/cdn_domain_list.txt
    auto_reload: true
  - tag: adlist
    file: ./rules/ad_domain_list.txt
    auto_reload: true
  - tag: ptrlocal
    file: ./rules/ptr_local_list.txt
    auto_reload: true
  - tag: ecscn
    file: ./ecs_cn_domain.txt
    auto_reload: true
  - tag: ecstw
    file: ./ecs_tw_domain.txt
    auto_reload: true
  - tag: hosts
    file: ./hosts.txt
    auto_reload: true

plugins:
  # 缓存的插件
  - tag: cache
    type: cache
    args:
      size: 5000
      compress_resp: true
      lazy_cache_ttl: 86400
      cache_everything: true
      lazy_cache_reply_ttl: 3

  # IP反查域名的插件
  - tag: reverse_lookup
    type: reverse_lookup
    args:
      size: 1000
      ttl: 3600
      handle_ptr: true

  # Hosts的插件
  - tag: hosts
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  # 调整ECS的插件
  - tag: ecs_client
    type: ecs
    args:
      auto: false
      ipv4: "1.2.4.0"
      mask4: 24
      force_overwrite: true
  - tag: ecs_tw
    type: ecs
    args:
      auto: false
      ipv4: "101.101.101.0"
      mask4: 22
      force_overwrite: true

  # 调整TTL的插件
  - tag: ttl_short
    type: ttl
    args:
      minimal_ttl: 60
      maximum_ttl: 3600
  - tag: ttl_long
    type: ttl
    args:
      minimal_ttl: 600
      maximum_ttl: 86400

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "223.5.5.5"

  # 转发至分流服务器的插件
  - tag: forward_apad_pro
    type: fast_forward
    args:
      upstream:
        - addr: "https://ipv4.apad.pro/dns-query"
          #dial_addr: "ip:port"
          bootstrap: "119.29.29.29"
          enable_http3: true

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: "tls://8.8.4.4:853"
          #socks5: "127.0.0.1:1080"
          enable_pipeline: true

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:chinalist"

  # 匹配CDN域名的插件
  - tag: query_is_cdn_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:cdncn"

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "provider:adlist"

  # 匹配内网PTR域名的插件
  - tag: query_is_ptr_local
    type: query_matcher
    args:
      domain:
        - "provider:ptrlocal"

  # 匹配强制中国大陆解析域名的插件
  - tag: query_is_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecscn"

  # 匹配强制中国台湾解析域名的插件
  - tag: query_is_tw_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecstw"

  # 匹配TYPE12类型请求的插件
  - tag: qtype12
    type: query_matcher
    args:
      qtype: [12]

  # 匹配TYPE65类型请求的插件
  - tag: qtype65
    type: query_matcher
    args:
      qtype: [65]
      
  # 屏蔽请求的插件
  - tag: black_hole
    type: blackhole
    args:
      rcode: 0
      ipv4: "127.0.0.1"
      ipv6: "::1"

  # 匹配RCODE2的插件
  - tag: response_server_failed
    type: response_matcher
    args:
      rcode: [2]

  # 匹配Akamai的插件
  - tag: query_is_akamai
    type: query_matcher
    args:
      domain:
        - ".akamaiedge.net"
        - ".akadns.net"
        - ".edgekey.net"
        - ".tl88.net"
        - ".akamaitechnologies.com"

  # 匹配内网域名的插件
  - tag: query_is_lan_domain
    type: query_matcher
    args:
      domain:
        - ".lan"

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义
  # 否则 sequence 找不到对应插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 域名映射IP
        - hosts

        # IP反查
        - reverse_lookup

        # ECS
        #- ecs_client
        #- _edns0_filter_ecs_only

        # 缓存
        - cache

        # 屏蔽内网PTR域名请求
        - if: "(query_is_ptr_local) && [qtype12]"
          exec:
            - black_hole
            - _return
            
        # 屏蔽TYPE65类型请求
        - if: qtype65
          exec:
            - black_hole
            - _return

        # 强制用本地服务器解析
        - if: query_is_cn_domain
          exec:
            - forward_local
            - _return

        # 强制用远程服务器解析
        - if: query_is_tw_domain
          exec:
            - ecs_tw
            - forward_apad_pro
            - ttl_long
            - _return

        # 屏蔽广告域名与内网域名
        - if: "(query_is_ad_domain) || (query_is_lan_domain)"
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的本地域名与CDN域名用本地服务器解析
        - if: "(query_is_local_domain) || (query_is_cdn_cn_domain) || (query_is_akamai) || [qtype12]"
          exec:
            - primary:
                - forward_local
              secondary:
                - forward_apad_pro
              fast_fallback: 50
              always_standby: true
            - ttl_short
            - _return

        # 剩下的域名用远程服务器解析
        - primary:
            - forward_apad_pro
          secondary:
            - forward_remote
          fast_fallback: 500
          always_standby: false
        - ttl_long

servers:
  - exec: main_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: "0.0.0.0:53"
      - protocol: tcp
        addr: "0.0.0.0:53"
